//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AstroStudio.rc
//
#define IDD_ABOUTBOX                    100
#define ID_VIEW_RETRO                   101
#define IDD_CHARTDETAILS                101
#define ID_VIEW_SECONDS                 102
#define ID_FONT_BIGGER                  103
#define ID_FONT_SMALLER                 104
#define ID_FONT_SIZE_DEFAULT            105
#define ID_VIEW_GRIDLINES               106
#define IDD_NEWCHART                    107
#define IDD_EPHEMERISOPTIONS            232
#define IDD_ASPECTOPTIONS               233
#define IDR_MAINFRAME                   128
#define IDS_TITLE                       129
#define IDR_FONT                        201
#define IDI_COLORWHEEL                  203
#define IDI_FONT                        204
#define IDI_GLYPH                       205
#define IDI_EPHEMERIS                   206
#define IDI_RETRO                       207
#define IDI_CLOCK                       208
#define IDI_FONT_BIGGER                 210
#define IDI_FONT_SMALLER                211
#define IDI_EVENT                       212
#define IDI_FONT_SIZE_DEFAULT           213
#define IDI_ICON1                       214
#define IDI_GRID                        214
#define IDI_COPY                        215
#define IDI_PIN                         216
#define IDI_CHART                       217
#define IDR_CONTEXT                     218
#define IDI_CUT                         220
#define IDI_PASTE                       221
#define IDI_PLAY                        222
#define IDI_STOP                        223
#define IDI_CHARTNOW                    224
#define IDI_GLOBE                       225
#define IDI_BACK                        226
#define IDI_FORWARD                     227
#define IDI_OPEN                        228
#define IDI_PRINT                       229
#define IDI_ICON4                       230
#define IDI_SAVE                        230
#define IDI_SAVEAS                      231
#define IDC_HOUSESYSTEM                 1000
#define IDC_PLANETS                     1001
#define IDC_DATE                        1002
#define IDC_TIME                        1003
#define IDC_HARMONIC                    1004
#define IDC_HOUSES                      1005
#define IDC_HARMONICUD                  1006
#define IDC_LOCATION                    1007
#define IDC_NAME                        1008
#define IDC_LATDEG                      1009
#define IDC_LATDEGUD                    1010
#define IDC_NORTH                       1011
#define IDC_SOUTH                       1012
#define IDC_HERE                        1015
#define IDC_LOOKUP                      1016
#define IDC_HERE2                       1017
#define IDC_APPLY                       1017
#define IDC_MONTHCALENDAR1              1018
#define IDC_LATMIN                      1019
#define IDC_LATMINUD                    1020
#define IDC_LONDEG                      1021
#define IDC_LONDEGUD                    1022
#define IDC_EAST                        1023
#define IDC_WEST                        1024
#define IDC_LONMIN                      1025
#define IDC_LONMINUD                    1026
#define IDC_NOW                         1027
#define IDC_DAY                         1028
#define IDC_MONTH                       1029
#define IDC_YEAR                        1030
#define IDC_TIMEZONE                    1031
#define IDC_MANUALTZ                    1032
#define IDC_TZOFFSET                    1033
#define IDC_CHARTTYPE                   1034
#define IDC_STEPCOUNT                   1035
#define IDC_STEPUNIT                    1036
#define IDC_STEPINTERVAL                1037
#define IDC_EPH_TODAY                   1040
#define IDC_EPH_STEP                    1041
#define IDC_EPH_BODIES                  1042
#define IDC_EPH_ECLIPSES                1043
#define IDC_EPH_VOID                    1044
#define IDC_EPH_STANDARD                1045
#define IDC_EPH_ALL                     1046
#define IDC_ASP_SET                     1047
#define IDC_ASP_MAJORORB                1048
#define IDC_ASP_MINORORB                1049
#define IDC_ASP_MAJORONLY               1050
#define IDC_ASP_ASPECTS                 1051
#define IDC_ASP_ORB                     1052
#define IDC_ASP_PLANETS                 1053
#define IDC_ASP_EXTRA                   1054
#define IDC_ASP_LOAD                    1055
#define IDC_ASP_SAVE                    1056
#define IDC_ASP_DEFAULTS                1057
#define IDC_SYSLINK1                    1038
#define IDC_LINK                        1038
#define ID_WINDOW_CLOSE                 32772
#define ID_WINDOW_CLOSE_ALL             32773
#define ID_OPTIONS_ALWAYSONTOP          32775
#define ID_TOOL_EPHEMERIS               32776
#define ID_VIEW_GLYPHS                  32777
#define ID_OPTIONS_FONT                 32778
#define ID_FILE_NEW32779                32779
#define ID_NEW_CHART                    32780
#define ID_NEW_CHARTFORNOW              32781
#define ID_OPTIONS_THEME                32782
#define ID_THEME_LIGHT                  32783
#define ID_THEME_DARK                   32784
#define ID_THEME_CLASSIC                32785
#define ID_THEME_SYSTEM                 32786
#define ID_OPTIONS_DARKMODE             32787
#define ID_CHART_STEP_BACK              32788
#define ID_CHART_STEP_FORWARD           32789
#define ID_CHART_AUTOSTEP               32790
#define ID_FILE_EXPORT                  32791
#define ID_CHART_LIVE                   32792
#define ID_CHART_TRANSITS               32793
#define ID_EPHEMERIS_OPTIONS            32794
#define ID_OPTIONS_ASPECTS              32795

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        234
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
